[package]
name = "flash"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.27.6"
serde_json = "1.0"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] } 
axum = "0.7.9"
tokio = { version = "1.42.0", features = ["full"]  }

